// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PK.Learn.Core.Service.DBModel;

public partial class Student
{
    public int StudentId { get; set; }

    public string Name { get; set; }

    public int? MajorId { get; set; }

    public int? Age { get; set; }

    public string MobileNo { get; set; }

    public string EmailId { get; set; }

    public DateOnly? Dob { get; set; }
}